export enum Category {
  CIENCIA = 'CIENCIA',
  ESPORTE = 'ESPORTE',
  ENTRETENIMENTO = 'ENTRETENIMENTO',
  HISTORIA = 'HISTORIA',
  GEOGRAFIA = 'GEOGRAFIA',
  ATUALIDADE = 'ATUALIDADE',
  TECNOLOGIA = 'TECNOLOGIA',
  MEIO_AMBIENTE = 'MEIO_AMBIENTE',
  MITOS_E_LENDAS = 'MITOS_E_LENDAS',
  CULINARIA = 'CULINARIA'
}
